name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Get Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install podman libopenal-dev

    - name: anaylse simd
      run: |
        podman pull ghcr.io/jimmarshall35/simd-detective:main
        podman run --rm --volume ./core:/zzfx-core simd-detective:main \
          simd-detective -f /zzfx-core/src/ZzFX.c \
          --list-operation \
          --list-info \
          --list-cpuid

    - name: Build
      run: |
        mkdir ./build
        cd build
        cmake ..
        make
        # package
        cd ..
        mkdir -p ./pkg/usr/bin
        mkdir -p ./pkg/usr/lib
        mkdir -p ./pkg/usr/include/zzfx
        cp ./python/zzfx.py ./pkg/usr/bin/zzfx.py
        cp ./python/zzfx.py ./pkg/usr/bin/zzfx_cli
        cp ./python/zzfx.py ./pkg/usr/bin/zzfx_gui
        chmod +x ./pkg/usr/bin/zzfx_cli
        chmod +x ./pkg/usr/bin/zzfx_gui
        cp ./build/core/libZzFX.a ./pkg/usr/lib/libZzFX.a
        cp ./build/openal_backend/libZzFX_OpenAL.so ./pkg/usr/lib/libZzFX_OpenAL.so
        cp -r ./core/include/*.h ./pkg/usr/include/zzfx

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./pkg # or path/to/artifact

